# Generated by Django 3.1 on 2021-03-30 13:21

import commercial.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Username',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=39, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username may only contain alphanumeric characters or hyphens & cannot have multiple consecutive hyphens & cannot begin or end with a hyphen', regex='^(?!-)(?!.*--)[a-zA-Z\\d)-]+(?<!-)$'), commercial.validators.validate_reserved_words])),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_users.username_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
    ]
