# Generated by Django 3.1 on 2021-03-16 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work', '0059_auto_20210311_1122'),
        ('talent', '0025_person_test_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributorAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_content', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.product')),
            ],
            options={
                'db_table': 'license_contributor_agreement',
            },
        ),
        migrations.CreateModel(
            name='ContributorAgreementAcceptance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='license.contributoragreement')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talent.person')),
            ],
            options={
                'db_table': 'license_contributor_agreement_acceptance',
            },
        ),
    ]
